---
- name: Clear any stale update-lock from a previous interrupted run
  become: true
  ansible.builtin.systemd_service:
    name: update-lock.service
    state: stopped
  register: clear_stale_lock
  failed_when:
    - clear_stale_lock.failed
    - "'Could not find the requested service' not in clear_stale_lock.msg"

- name: Prevent system from suspending while updates are being applied
  become: true
  ansible.builtin.command:
    cmd: systemd-run --unit=update-lock systemd-inhibit --what=sleep --why="Ansible update running" sleep infinity
  changed_when: true

- name: Check for ostree updates
  become: true
  ansible.builtin.command:
    cmd: rpm-ostree upgrade --check
  register: ostree_updates
  changed_when: false
  failed_when:
    - ostree_status.rc != 0
    - "'No updates available' not in ostree_status.stdout"

- name: Run ostree updates when available
  become: true
  ansible.builtin.command:
    cmd: rpm-ostree upgrade
  when: "'Diff: ' in ostree_updates.stdout"
  changed_when: true
  notify: Reboot device

- name: "Update flatpaks on system"
  become: true
  community.general.flatpak:
    name: "{{ item }}"
    state: latest
    method: system
  loop: "{{ flatpak_apps }}"

# TODO update admin toolbox apps
# - name: Update existing packages installed in admin toolbox
#   become: true
#   become_user: "{{ parent_username }}"
#   ansible.builtin.command:
#     cmd: >
#       toolbox run --container {{ toolbox_name }}
#       sudo dnf upgrade --assumeyes --quiet
#       {{ toolbox_apps | join(' ') }}
#   register: updated_packages
#   changed_when: "'Nothing to do' not in updated_packages.stdout"

- name: Remove system update-lock after updates are complete
  become: true
  ansible.builtin.systemd_service:
    name: update-lock.service
    state: stopped
  register: remove_update_lock
  failed_when:
    - remove_update_lock.failed
    - "'Could not find the requested service' not in remove_update_lock.msg"
