# SPDX-License-Identifier: MIT-0
---
# tasks file for user_accounts
- name: "Create user: {{ child_username }}"
  become: true
  ansible.builtin.user:
    name: "{{ child_username }}"
    state: present
    password: '!'
    expires: -1

- name: Create parent privileged user
  become: true
  ansible.builtin.user:
    name: "{{ parent_username }}"
    state: present
    password: "{{ parent_password | password_hash('sha512') }}"
    expires: -1
    groups: wheel
    append: true

- name: Create ansible service account
  become: true
  ansible.builtin.user:
    name: "{{ ansible_username }}"
    state: present
    password: "!"                                            # sets no password/password authentication cannot be used
    expires: -1
    groups: wheel
    append: true

- name: "Add ssh public key"
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    state: present
  loop:
    - {"user":"{{ parent_username }}", "key":"{{ parent_public_key }}"}
    - {"user":"{{ ansible_username }}", "key":"{{ ansible_public_key }}"}
  loop_control:
    label: "{{ item.user }}"

- name: Pre-create .ansible/tmp for each user to suppress remote_tmp warning
  become: true
  become_user: "{{ item }}"
  ansible.builtin.file:
    path: "~/.ansible/tmp"
    state: directory
    mode: '0700'
  loop:
    - "{{ parent_username }}"
    - "{{ ansible_username }}"
    - "{{ child_username }}"

- name: "Enable autologin for {{ child_username }}"
  become: true
  community.general.ini_file:
    path: /etc/lightdm/lightdm.conf
    section: Seat:*
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: "0644"
    state: present
  loop:
    - {"option":"autologin-user", "value":"{{ child_username }}"}
    - {"option":"autologin-user-timeout", "value":"0"}

- name: "Enable passwordless sudo for {{ ansible_username }}"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ ansible_username }}"
    state: present
    line: "{{ ansible_username }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    mode: "0440"
    validate: /usr/sbin/visudo -cf %s
